// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7zIHPdDSyLQSloeyYUo2OX4jLt07RYK8',
    appId: '1:647250430928:web:59e33926f393615de887d5',
    messagingSenderId: '647250430928',
    projectId: 'cellulo-hub-games',
    authDomain: 'cellulo-hub-games.firebaseapp.com',
    storageBucket: 'cellulo-hub-games.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-rpiGCDAUXScHzmUXAhaIuSTJ5cP7SwE',
    appId: '1:647250430928:android:cb2c127e5394e772e887d5',
    messagingSenderId: '647250430928',
    projectId: 'cellulo-hub-games',
    storageBucket: 'cellulo-hub-games.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcbRk0w8NGfVFOeUCoN7_4H0Btz8UX92U',
    appId: '1:647250430928:ios:6ca3d62b71180744e887d5',
    messagingSenderId: '647250430928',
    projectId: 'cellulo-hub-games',
    storageBucket: 'cellulo-hub-games.appspot.com',
    iosClientId:
        '647250430928-cgen993vmnbp97t5avcbkspbbtkuv7d2.apps.googleusercontent.com',
    iosBundleId: 'com.chili.celluloHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcbRk0w8NGfVFOeUCoN7_4H0Btz8UX92U',
    appId: '1:647250430928:ios:6ca3d62b71180744e887d5',
    messagingSenderId: '647250430928',
    projectId: 'cellulo-hub-games',
    storageBucket: 'cellulo-hub-games.appspot.com',
    iosClientId:
        '647250430928-cgen993vmnbp97t5avcbkspbbtkuv7d2.apps.googleusercontent.com',
    iosBundleId: 'com.chili.celluloHub',
  );
}
